[FAB-7549] Silence Usage once command args are parsed
This patch stops the display of the command usage message once the
arguments have been successfully parsed so that the user isn't led
to believe the error they got has something to do with how they
invoked the peer command.

Before this patch when an error occurs the command usage is displayed
even when the error isn't related to usage:

$ ./peer chaincode query -C mychannel -n mywrongcc -c '{"Args":["query","a"]}'
2018-03-08 14:36:39.292 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2018-03-08 14:36:39.292 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: Error endorsing query: rpc error: code = Unknown desc = make sure the chaincode mywrongcc has been successfully instantiated and try again: could not find chaincode with name 'mywrongcc' - <nil>
Usage:
  peer chaincode query [flags]

Flags:
  -C, --channelID string   The channel on which this command should be executed
  -c, --ctor string        Constructor message for the chaincode in JSON format (default "{}")
  -x, --hex                If true, output the query value byte array in
...
$

After this patch only the error is displayed:

$ ./peer chaincode query -C mychannel -n mywrongcc -c '{"Args":["query","a"]}'
2018-03-19 12:26:16.250 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 001 Using default escc
2018-03-19 12:26:16.250 UTC [chaincodeCmd] checkChaincodeCmdParams -> INFO 002 Using default vscc
Error: Error endorsing query: rpc error: code = Unknown desc = make sure the chaincode mywrongcc has been successfully instantiated and try again: could not find chaincode with name 'mywrongcc' - <nil>
$

The usage message is still displayed in case the error actually comes
from the way the command is being invoked:

$ ./peer chaincode query -C mychannel -n
Error: flag needs an argument: 'n' in -n
Usage:
  peer chaincode query [flags]

Flags:
  -C, --channelID string   The channel on which this command should be executed
...
$

Change-Id: I5a705ea0b3fb75c3b879b1429338f756e7325b74
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>