Update secured_private_asset_transfer_tutorial.md
Current command causes 
Error: error parsing transient string: invalid character '\n' in string literal - proposal response: <nil>

Proposing to update command to be the same as the release-2.4 docs @ https://hyperledger-fabric.readthedocs.io/en/release-2.4/secured_asset_transfer/secured_private_asset_transfer_tutorial.html