[FAB-13663] refactor getChaincodeDeploymentSpec
The purpose is to support dev mode.

In dev mode, when we run:
    peer chaincode install -n mycc -v 1.0 -l golang -p github.com/example02
It will return:
    Error: Bad response: 500 - nil code package

Because "chaincode.IsDevMode() == false", see below code:

func getChaincodeDeploymentSpec(spec *pb.ChaincodeSpec, crtPkg bool) (*pb.ChaincodeDeploymentSpec, error) {
    ...
    if chaincode.IsDevMode() == false && crtPkg {
    ...
        codePackageBytes, err = container.GetChaincodePackageBytes(platformRegistry, spec)
    ...
    }
    ...
}

That is, in dev mode, getChaincodeDeploymentSpec did not get chaincode packageBytes, also we can find the reason from the code flow:
lscc Invoke()->executeInstall()->ExtractStatedbArtifactsForChaincode->ExtractStatedbArtifactsFromCCPackage->GetMetadataAsTarEntries()->getCode()

func (tgzProv *TargzMetadataProvider) getCode() ([]byte, error) {
    if tgzProv.Code == nil {
        return nil, errors.New("nil code package")
    }
    return tgzProv.Code, nil
}

So, if we remove "chaincode.IsDevMode() == false &&", all will ok.

Change-Id: Ib0caee75ebc44b73c912ebdcabfca21389dddde5
Signed-off-by: kutenglaoshu <1065239881@qq.com>